# A S Alam <aalam@fedoraproject.org>, 2017. #zanata
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2018-04-06 07:47+0200\n"
"PO-Revision-Date: 2017-08-18 07:13-0400\n"
"Last-Translator: A S Alam <aalam@fedoraproject.org>\n"
"Language-Team: Punjabi\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: pa\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"X-Generator: Zanata 3.9.6\n"

#. Translators: This string is only used in unit tests.
#: ../plugins/system_upgrade.py:38
msgid "the color of the sky"
msgstr "ਅਸਮਾਨ ਦਾ ਰੰਗ"

#: ../plugins/system_upgrade.py:54
msgid "Need a --releasever greater than the current system version."
msgstr ""

#. Translators: do not change "reboot" here
#: ../plugins/system_upgrade.py:56
msgid ""
"Download complete! Use 'dnf system-upgrade reboot' to start the upgrade.\n"
"To remove cached metadata and transaction use 'dnf system-upgrade clean'"
msgstr ""

#: ../plugins/system_upgrade.py:59
msgid "Sorry, you need to use 'download --releasever' instead of '--network'"
msgstr ""

#: ../plugins/system_upgrade.py:235
msgid "The following boots appear to contain upgrade logs:"
msgstr ""

#: ../plugins/system_upgrade.py:245
msgid "-- no logs were found --"
msgstr "-- ਕੋਈ ਲਾਗ ਨਹੀਂ ਲੱਭਿਆ --"

#: ../plugins/system_upgrade.py:260
msgid "Cannot find logs with this index."
msgstr ""

#: ../plugins/system_upgrade.py:269
msgid "Unable to match systemd journal entry"
msgstr ""

#: ../plugins/system_upgrade.py:288
msgid "Prepare system for upgrade to a new release"
msgstr "ਸਿਸਟਮ ਨੂੰ ਨਵੇਂ ਰੀਲਿਜ਼ ਵਾਸਤੇ ਅੱਪਗਰੇਡ ਲਈ ਤਿਆਰ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ"

#: ../plugins/system_upgrade.py:298
msgid "keep installed packages if the new release's version is older"
msgstr ""

#: ../plugins/system_upgrade.py:302
msgid "which logs to show"
msgstr ""

#: ../plugins/system_upgrade.py:345
msgid ""
"Before you continue ensure that your system is fully upgraded by running "
"\"dnf --refresh upgrade\". Do you want to continue"
msgstr ""

#: ../plugins/system_upgrade.py:349
msgid "Operation aborted."
msgstr ""

#: ../plugins/system_upgrade.py:400
msgid "system is not ready for upgrade"
msgstr "ਸਿਸਟਮ ਅੱਪਗਰੇਡ ਕਰਨ ਲਈ ਤਿਆਰ ਨਹੀਂ ਹੈ"

#: ../plugins/system_upgrade.py:402
msgid "upgrade is already scheduled"
msgstr "ਅੱਪਗਰੇਡ ਲਈ ਪਹਿਲਾਂ ਹੀ ਸਮਾਂ ਤਹਿ ਕੀਤਾ ਗਿਆ"

#: ../plugins/system_upgrade.py:407
msgid "trigger file does not exist. exiting quietly."
msgstr ""

#: ../plugins/system_upgrade.py:410
msgid "another upgrade tool is running. exiting quietly."
msgstr "ਹੋਰ ਅੱਪਗਰੇਡ ਟੂਲ ਚੱਲ ਰਿਹਾ ਹੈ। ਬੰਦ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ।"

#. Translators: do not change "reboot" here
#: ../plugins/system_upgrade.py:416
msgid "use 'dnf system-upgrade reboot' to begin the upgrade"
msgstr "ਅੱਪਗਰੇਡ ਸ਼ੁਰੂ ਕਰਨ ਲਈ 'dnf system-upgrade reboot' ਵਰਤੋ"

#: ../plugins/system_upgrade.py:436
msgid "Rebooting to perform upgrade."
msgstr "ਅੱਪਗਰੇਡ ਕਰਨ ਲਈ ਮੁੜ-ਚਾਲੂ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ।"

#: ../plugins/system_upgrade.py:457 ../plugins/system_upgrade.py:463
msgid "Starting system upgrade. This will take a while."
msgstr "ਸਿਸਟਮ ਨੂੰ ਅੱਪਗਰੇਡ ਕਰਨਾ ਸ਼ੁਰੂ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ। ਇਸ ਨੂੰ ਕੁਝ ਸਮਾਂ ਲੱਗੇਗਾ।"

#: ../plugins/system_upgrade.py:489
#, python-format
msgid "Unable to match package: %s"
msgstr ""

#: ../plugins/system_upgrade.py:494
msgid "Unable to match some of packages"
msgstr ""

#: ../plugins/system_upgrade.py:497
msgid "Cleaning up downloaded data..."
msgstr "...ਡਾਊਨਲੋਡ ਕੀਤੇ ਡਾਟੇ ਨੂੰ ਸਾਫ਼ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ"

#: ../plugins/system_upgrade.py:531
msgid "Download finished."
msgstr "ਡਾਊਨਲੋਡ ਕਰਨਾ ਪੂਰਾ ਹੋਇਆ।"

#: ../plugins/system_upgrade.py:535 ../plugins/system_upgrade.py:536
msgid "Upgrade complete! Cleaning up and rebooting..."
msgstr "ਅੱਪਗਰੇਡ ਪੂਰਾ ਹੋਇਆ! ਸਾਫ਼ ਕਰਕੇ ਮੁੜ-ਚਾਲੂ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ..."

#: ../plugins/tracer.py:70
msgid "For more information run:"
msgstr "ਹੋਰ ਜਾਣਕਾਰੀ ਲਈ ਚਲਾਓ:"

#: ../plugins/tracer.py:97
msgid "Call to Tracer API ended unexpectedly:"
msgstr ""

#: ../plugins/tracer.py:99
msgid ""
"Please visit https://github.com/FrostyX/tracer/issues and submit the issue. "
"Thank you"
msgstr ""

#: ../plugins/tracer.py:101
msgid "We apologize for any inconvenience"
msgstr "ਕਿਸੇ ਵੀ ਆਈ ਸਮੱਸਿਆ ਲਈ ਸਾਨੂੰ ਅਫ਼ਸੋਸ ਹੈ"

#: ../plugins/rpm_conf.py:69
msgid "Adding '{}' to list of handling packages for rpmconf"
msgstr ""

#: ../plugins/rpm_conf.py:75
msgid "rpmconf plugin will not run in non-interactive mode"
msgstr ""

#: ../plugins/rpm_conf.py:88
msgid "ignoring sys.exit from rpmconf due to missing MERGE variable"
msgstr ""

#: ../plugins/rpm_conf.py:92
msgid "ignoring sys.exit from rpmconf due to missing file"
msgstr ""

#: ../plugins/snapper.py:49
#, python-format
msgid "connect to snapperd failed: %s"
msgstr ""

#: ../plugins/snapper.py:55
msgid "creating pre_snapshot"
msgstr ""

#: ../plugins/snapper.py:61
#, python-format
msgid "created pre_snapshot %d"
msgstr ""

#: ../plugins/snapper.py:65
#, python-format
msgid "creating pre_snapshot failed: %s"
msgstr ""

#: ../plugins/snapper.py:71
msgid "skipping post_snapshot because creation of pre_snapshot failed"
msgstr ""

#: ../plugins/snapper.py:77
msgid "creating post_snapshot"
msgstr ""

#: ../plugins/snapper.py:82
#, python-format
msgid "created post_snapshot %d"
msgstr ""

#: ../plugins/snapper.py:86
#, python-format
msgid "creating post_snapshot failed: %s"
msgstr ""

#: ../plugins/kickstart.py:59
msgid "Install packages defined in a kickstart file on your system"
msgstr ""

#: ../plugins/kickstart.py:64
msgid "kickstart file"
msgstr "ਕਿੱਕਸਟਾਰਟ ਫਾਇਲ"

#: ../plugins/kickstart.py:82
#, python-format
msgid "file cannot be parsed: %s"
msgstr "ਫਾਇਲ ਨੂੰ ਪਾਰਸ ਨਹੀਂ ਕੀਤਾ ਜਾ ਸਕਦਾ: %s"

#: ../plugins/kickstart.py:99
#, python-format
msgid "No package %s available."
msgstr "%s ਪੈਕੇਜ ਉਪਲਬਧ ਨਹੀਂ ਹੈ।"

#: ../plugins/kickstart.py:104
msgid "Nothing to do."
msgstr "ਕਰਨ ਲਈ ਕੁਝ ਨਹੀਂ ਹੈ।"

#: ../plugins/torproxy.py:32
msgid "Disabling torproxy plugin: cannot connect to the Tor network"
msgstr ""
